DWD278-FinalProject-VH/Controllers/ToWatchListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DWD278_FinalProject_VH.Models;

namespace DWD278_FinalProject_VH.Controllers
{
    public class ToWatchListsController : Controller
    {
        private ToWatchListContext db = new ToWatchListContext();

        // GET: ToWatchLists
        public ActionResult Index()
        {
            var toWatchList = db.ToWatchList.Include(t => t.Genre).Include(t => t.Rating).Include(t => t.TypeStatus);
            return View(toWatchList.ToList());
        }

    

        // GET: ToWatchLists/Create
        public ActionResult Create()
        {
            ViewBag.GenreID = new SelectList(db.Genre, "ID", "Description");
            ViewBag.RatingID = new SelectList(db.Rating, "ID", "Description");
            ViewBag.TypeStatusID = new SelectList(db.TypeStatus, "ID", "Description");
            return View();
        }

        // POST: ToWatchLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Year,GenreID,RatingID,Description,TypeStatusID")] ToWatchList toWatchList)
        {
            if (ModelState.IsValid)
            {
                db.ToWatchList.Add(toWatchList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenreID = new SelectList(db.Genre, "ID", "Description", toWatchList.GenreID);
            ViewBag.RatingID = new SelectList(db.Rating, "ID", "Description", toWatchList.RatingID);
            ViewBag.TypeStatusID = new SelectList(db.TypeStatus, "ID", "Description", toWatchList.TypeStatusID);
            return View(toWatchList);
        }

        // GET: ToWatchLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToWatchList toWatchList = db.ToWatchList.Find(id);
            if (toWatchList == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenreID = new SelectList(db.Genre, "ID", "Description", toWatchList.GenreID);
            ViewBag.RatingID = new SelectList(db.Rating, "ID", "Description", toWatchList.RatingID);
            ViewBag.TypeStatusID = new SelectList(db.TypeStatus, "ID", "Description", toWatchList.TypeStatusID);
            return View(toWatchList);
        }

        // POST: ToWatchLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Year,GenreID,RatingID,Description,TypeStatusID")] ToWatchList toWatchList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toWatchList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenreID = new SelectList(db.Genre, "ID", "Description", toWatchList.GenreID);
            ViewBag.RatingID = new SelectList(db.Rating, "ID", "Description", toWatchList.RatingID);
            ViewBag.TypeStatusID = new SelectList(db.TypeStatus, "ID", "Description", toWatchList.TypeStatusID);
            return View(toWatchList);
        }

        // GET: ToWatchLists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToWatchList toWatchList = db.ToWatchList.Find(id);
            if (toWatchList == null)
            {
                return HttpNotFound();
            }
            return View(toWatchList);
        }

        // POST: ToWatchLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToWatchList toWatchList = db.ToWatchList.Find(id);
            db.ToWatchList.Remove(toWatchList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DWD278-FinalProject-VH/Controllers/TypeStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DWD278_FinalProject_VH.Models;

namespace DWD278_FinalProject_VH.Controllers
{
    public class TypeStatusController : Controller
    {
        private ToWatchListContext db = new ToWatchListContext();

        // GET: TypeStatus
        public ActionResult Index()
        {
            return View(db.TypeStatus.ToList());
        }

 

        // GET: TypeStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description")] TypeStatus typeStatus)
        {
            if (ModelState.IsValid)
            {
                db.TypeStatus.Add(typeStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(typeStatus);
        }

        // GET: TypeStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeStatus typeStatus = db.TypeStatus.Find(id);
            if (typeStatus == null)
            {
                return HttpNotFound();
            }
            return View(typeStatus);
        }

        // POST: TypeStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description")] TypeStatus typeStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(typeStatus);
        }

        // GET: TypeStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeStatus typeStatus = db.TypeStatus.Find(id);
            if (typeStatus == null)
            {
                return HttpNotFound();
            }
            return View(typeStatus);
        }

        // POST: TypeStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TypeStatus typeStatus = db.TypeStatus.Find(id);
            db.TypeStatus.Remove(typeStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DWD278-FinalProject-VH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Watch List", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">S
                <ul class="nav navbar-nav">
                  
                    <li>@Html.ActionLink("Add To List", "Index", "ToWatchLists")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="nav-item dropdown-toggle">
                        <a href="#" data-toggle="dropdown" id="maintenanceDropdown">Updates ▼</a>
                        <ul class="dropdown-menu" areia-labelledby="maintenanceDropdown">
                            <li>@Html.ActionLink("Genre", "Index", "Genre")</li>
                            <li>@Html.ActionLink("Rating", "Index", "Rating")</li>
                            <li>@Html.ActionLink("Movie/Show", "Index", "TypeStatus")</li>
                        </ul>
</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <img src="https://paztofilm.files.wordpress.com/2011/11/cropped-cropped-film_header22.jpg" alt="Moives" style="width:1140px; height:180px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Victoria Humphrey's ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>